### ISSUE TITLE
DMD audio not muting

### ISSUE THREAD

**Issue by jsb2092** [mjrgh/PinballY#118]
I have color DMD videos that have audio.  These play fine through the system but when I select mute videos they do not mute.  When selecting mute audio during attract mode they also do not mute. Adjusting the audio level for the table that the dmd video is for does cause the video volume to go down. 

The files are located in Media\<system folder>\Real DMD Color Videos
They are playing on a real DMD (PinDMD3)

**Comment by mjrgh** [comment]
This should be fixed in the Beta 21.

**Comment by jsb2092** [comment]
Not fixed.  Muting Videos does not mute DMD videos and audio still plays in attract mode, running beta 21

**Comment by jsb2092** [comment]
More information - the issue is that the audio state resets when the table changes. If I have mute videos on one table, and change to another table, it's no longer muted even though the option is selected. Since the attract mode switches tables, the audio is not muted for that either.
